### PR TITLE
Added Blue/Green-Deployment

### PR DESCRIPTION
**Pull request by samedguener**
- Please refer to https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html and https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry for reference
- fixed issue, where app won't start after new upload

### CODE REVIEW

**Comment by ArthurHlt** [comment]
Thank you for your contribution.
We actually plan to add blue green deployment but we need to discuss with @mevansam about what strategy to adopt.

You can join us on the opened discussion https://github.com/mevansam/terraform-provider-cf/issues/25

**Comment by gberche-orange** [comment]
@samedguener besides blue green support #25, this pr mentions "fixed issue, where app won't start after new upload". 

Would you mind submitting a distinct PR for this issue with a description of the symptoms when the issue reproduces ?

I close this pr for now until we resume #25 

thanks again!

**Comment by samedguener** [comment]
Opened an issue for this, describing the problem [#32](https://github.com/mevansam/terraform-provider-cf/issues/32).

Best,
Samed

**Comment by gberche-orange** [comment]
thanks @samedguener !

**Pull request closed without merging**
