### PR TITLE
stop downloading the app asynchronously

### PR DESCRIPTION
**Pull request by jcarrothers-sap**
This is the original source of the change in #87 and covers #88

### CODE REVIEW

**Comment by bgandon** [comment]
Would it be possible that you remove your changes to `CONTRIBUTING.md` and ` website/docs/r/app.html.markdown` as they don't belong to the feature?

**Comment by janosbinder** [comment]
@bgandon that is basically a side effect that I also had. This PR should solve that https://github.com/mevansam/terraform-provider-cf/pull/90

**Comment by gberche-orange** [comment]
@janosbinder to merge https://github.com/jcarrothers-sap/terraform-provider-cf/pull/1 and submit a new PR from mevansam/terraform-provider-cf repo

**Comment by jcarrothers-sap** [comment]
Closing in favour of #132

**Pull request closed without merging**
