### PR TITLE
Got fixAppUpdates from Jim's branch

### PR DESCRIPTION
**Pull request by janosbinder**
Contains a test, which makes it fail, unless Jim's patch is merged

### CODE REVIEW

**Comment by janosbinder** [comment]
@j
I tried to merge your changes, but it seems it won't be trivial as it breaks the tests. Probably this is due to the docker support that we merged recently.

**Comment by jcarrothers-sap** [comment]
@janosbinder The changes necessary for docker support don't seem particularly complicated, especially not within the `resourceAppUpdate` method.  

I take it the test you have added to this branch replicated the update problem we've been seeing?  If so, would it make more send for you to add it to the branch in my fork and I'll merge it there?  I'll hopefully be pushing up a merge to resolve these conflicts soon.

**Comment by gberche-orange** [comment]
@jcarrothers-sap @janosbinder what don't you both work on a new common branch on the mevansam/terraform-provider-cf repo, so that the whole team can benefit from the travis-ci test results on the acceptance tests ?

**Comment by janosbinder** [comment]
@jcarrothers-sap

I have managed to merged the branches. This contains your fixes on `jcarrothers-sap:fixAppUpdates `, plus a test which fails, unless this your fixes are there, plus a small fix to make the test working for docker images. Let me know whether it is useful for you. Otherwise we can drop the `mevansam:fixAppUpdates` branch.

**Pull request merged**
