### PR TITLE
Added several imports

### PR DESCRIPTION
**Pull request by samedguener**
- import for cf_app, cf_route, cf_service_instance, cf_service_broker, cf_domain, cf_space, cf_org
- some attributes can't not be retrieved from Cloud Foundry, please refer to source code comments

### CODE REVIEW

**Comment by ArthurHlt** [comment]
Hi @samedguener thank you for your contribution. Maybe you missed it but it has been done in the PR #13, you can try it on the dev branch for now. 

Let us know if you think that some features are missing on import.

For now, I'm closing it.

**Comment by samedguener** [comment]
Hey @ArthurHlt thank you for the fast response! I had already seen your contribution in the dev branch. I want to point out what is actually missing in the imports: 

- import of cf_app: 

The attribute `credentials` can actually be retrieved from Cloud Foundry. Terraform handles non-string values such as maps in the first level using the default attributes such as `schema.TypeMap`. So you can actually parse this attribute successfully. Terraform doesn't fail at parsing in the first level, it fails when you try to parse a nested map. It seems like the current implementaion of @mevansam parses nested objects just as strings. I referred to this, while implementing. Please refer to `addServiceBindings` in `resource_cf_app.go` for reference.

Unfortunately, you missed the attribute `route` and `stopped` , which can also be retrieved completely from Cloud Foundry. The attribute `timeout` can be ignored for now.

Furthermore, I did not understand the reliability of getting the `url` attribute via the the call `/v2/apps/:guid/download`, would be please about the reasons!

- import of cf_space: 

Something went wrong here, it seems like you are trying to import cf_asg. I could also be wrong. Please correct me, if so.

- import of cf_service_broker:

Currently missing.

- import of cf_domain:

Currently missing.

- import of cf_route:

Currently missing.

- import of cf_server_instance:

Currently missing.

- import of cf_org:

Currently missing.

Thank you in advance for your response, I am looking forward to extend the provider!

Best,
Samed

**Comment by ArthurHlt** [comment]
Actually, all resources have import. Mostly, this is importable with just one line, e.g. for route : https://github.com/mevansam/terraform-provider-cf/blob/dev/cloudfoundry/resource_cf_route.go#L22

When it is a more specific resource, i've made separated file that's why.

For credentials on app, I prefer wait on this PR #24, the fact is that with import you can import an app which has an nested map as value.

About the part on route and start/stop state on app, it's because on https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/cfapi/app_manager.go it doesn't retrieve app status. Internally, use `ImportStatePassthrough` call a read on resource. 

I don't think route should be imported (as it is on read of route resource) because this was just made for a more convenient way to have a default route on your app. You can retrieve it from route import instead (@mevansam what is your though about that ? )

For url, I can remove if you want, it was only to be able to take code from the app and put it on another app if wanted.

**Comment by samedguener** [comment]
Thanks for your response 👍 

I don't understand how actually your imports are working, based on one line. Having a look into the [reference](https://github.com/hashicorp/terraform/blob/bb844504bd3a52ac990b5ff817f8ca18d6876714/helper/schema/resource_importer.go#L50), it declares that one shall use this if only and only id refreshes are possible. What about stuff like mappings etc? The main goal of a import should be to replicate everything as good as possible. 

Thanks for the update regarding the credentials. The best is to wait for this enhancement and then implement the missing things !

I think either remove the routes completely from cf_app or make it available. Because if you do not have the information about the routes, after import Terraform will see a plan change in cf_app and will try to update the app.

I would remove that, due to the fact that no information about the exact location where the app was downloaded can be retrieved. We should note that one can inject this value manually, if someone want to replicate as good as possible.

Best,
Samed

**Comment by ArthurHlt** [comment]
Sorry, I've do some shortcut to explain you how import was working on terraform.

You are obviously true when you say "the main goal of a import should be to replicate everything as good as possible". This is why this function was made to be able to import without think that much. 

The correct interpretation about "in the case that an ID-only refresh is possible" was actually about saying that, you, as provider developer, don't use other things than id of your service (in our case, on import org, this id given by cloud foundry for an org). ID-only is actually the most common usecase but that give us ability to let people use other things than ID given by service (you can have a look on kubernetes provider to see some examples).
Bu I do agree, this comment is really ambiguous but if it can be completed with the comment [just before](https://github.com/hashicorp/terraform/blob/bb844504bd3a52ac990b5ff817f8ca18d6876714/helper/schema/resource_importer.go#L20-L24).

In fact, to understand how import works, you need to test it.

## Example 

Your tf file:
```tf
resource "cf_org" "o1" {}
```

You want to retrieve state for an org, so you use the import state command (here my org is called pcfdev-org): `terraform import cf_org.o1 dde0caf3-35e8-4f0e-80ee-a390996aa5d8`

After import you will see that all informations has been retrieved in your state file:
```json
{
    "modules": [
        {
            "resources": {
                "cf_org.o1": {
                    "type": "cf_org",
                    "depends_on": [],
                    "primary": {
                        "id": "dde0caf3-35e8-4f0e-80ee-a390996aa5d8",
                        "attributes": {
                            "auditors.#": "0",
                            "billing_managers.#": "0",
                            "id": "dde0caf3-35e8-4f0e-80ee-a390996aa5d8",
                            "managers.#": "1",
                            "managers.1375426193": "1f175f0f-e8bf-42a8-bc89-c07bb157d9ff",
                            "name": "pcfdev-org",
                            "quota": "eebd901f-d76a-4621-8799-6e70cf9bff17"
                        }
                    }
                }
            },
            "depends_on": []
        }
    ]
}
```

**Comment by ArthurHlt** [comment]
About the route, yes indeed, it doesn't import the route attribute in state. (Because read doesn't set it). I didn't realize that's could be blocking. I will do the change.
this is more because this attribute doesn't exists that terraform see a change, not because it's not filled. (so it's, in fact, kind of "removed")

**Comment by samedguener** [comment]
@ArthurHlt  Thanks for your information!

I didn't know that the read function is actually called, when one uses the import functionality to import a cf resource.

I will check if any other attributes are missing and not being set by the read function.

Best,
Samed

**Comment by samedguener** [comment]
@ArthurHlt Are there any updates regarding the changes?

Best,
Samed

**Pull request closed without merging**
